name: ipcrypt
description: A Dart library for IP address encryption and obfuscation.
version: 0.1.2
repository: https://github.com/elliotwutingfeng/ipcrypt
funding:
    - https://www.buymeacoffee.com/elliotwutingfeng
topics:
    - crypto
    - cryptography
    - encryption
    - privacy
    - security

environment:
    sdk: ^3.9.0

dependencies:
    pointycastle: ^4.0.0

dev_dependencies:
    coverage: ^1.15.0
    lints: ^6.0.0
    test: ^1.28.0
